Added CosFace Loss
qdrant/quaterion pull request #202
Opened 2023-03-29 13:03 UTC by crsdvaibhav

- Added CosFace Loss, with tests and documentation.
- Moved `l2_norm` from ArcFace Loss to `quaterion.utils` and updated the imports and `__init__.py`

2023-03-29 13:06 UTC, crsdvaibhav commented
@monatis All checks have passed. Please could you review it? Thanks!

2023-03-30 05:50 UTC, monatis requested changes

2023-03-30 05:50 UTC, monatis commented on tests/eval/losses/test_cos_face_loss.py
> +        loss = CosFaceLoss()
You do not pass the required arguments to the loss in tests.

```suggestion
        loss = CosFaceLoss(self.embeddings.size()[1], 3)
```

2023-03-30 21:48 UTC, crsdvaibhav commented
@monatis Sorry, I must have missed changing it after reverting my commits. Thank you! Is there anything more before merging?

2023-03-31 09:34 UTC, monatis commented on quaterion/loss/cos_face_loss.py
> +
Let's make a proper assertion.

```suggestion
        assert groups.ge(0).all() and groups.lt(self.kernel.size(1)).all(), \
            f"Invalid group ids: all the values must be between 0 (inclusive) and num_groups (exclusive), but given:  {groups}"

```

2023-04-01 16:33 UTC, crsdvaibhav commented
@monatis Ran the tests locally. Made the requested changes. Anything more, to be done? Also, thankyou for the help!
<img width="658" alt="test_cos_face_loss" src="https://user-images.githubusercontent.com/95699355/229303083-7f2e566c-72c0-4237-9786-90a060f8960c.png">

2023-04-03 07:47 UTC, monatis commented
@crsdvaibhav ArcFace has the assertion missing, and CosFace has it twice. See also #203 (thanks @KarahanS)

2023-04-03 19:56 UTC, monatis approved these changes

2023-04-03 20:00 UTC, merged

2023-04-04 02:20 UTC, crsdvaibhav commented
> @crsdvaibhav ArcFace has the assertion missing, and CosFace has it twice. See also #203 (thanks @KarahanS)

I changed it. Thanks for the merge! I will move to #203